### ISSUE TITLE
login page: menu button top right for small screens dosn't work

### ISSUE THREAD

**Issue by pmario** [docker/hub-feedback#119]
to reproduce: 
- resize your browser window until it removes the top right login buttons

![docker-hub-small-screen](https://cloud.githubusercontent.com/assets/374655/8395634/30e36410-1d7d-11e5-998d-c4c8b0b60fd1.gif)
- the top right menu burger button doesn't work. 
- same problem with FF, Chrome and mobile device

**Comment by pmario** [comment]
If you are logged in, there is the same problem

**Comment by ChristopherBiscardi** [comment]
This is a particularly egregious example of #46 

I'm going to leave this as a separate ticket (bug) since it should be fixed whether or not the site is fully responsive.

**Comment by aptalca** [comment]
Fast forward a month and a half, the new website has been out for a couple of weeks and you still can't open the menu or login on a mobile device.

I thought docker raised hundreds of millions of dollars from VC's (over $160M as of April '15). Yet they can't even get the website right. Ouch!

**Comment by ahmetalpbalkan** [comment]
Folks please fix this. 

This is making the website useless on mobile. 

If you actually try to log in to Docker Hub from iOS right now
1. You can't login because no login form is shown
2. Hamburger button doesnt work
3. You gotta guess the url. (Luckily /login)

And now I'm in an emergency situation and could not add a member to my organization.


 Clearly someone tried to implement responsive design but nobody either bothered testing or we're trying to use a deliberately badly shipped product. It saddens me a great deal. 

Some style-less HTML page or bootstrap.css would be way more functional than what we got here. Please prioritize this.

**Comment by ChristopherBiscardi** [comment]
@ahmetalpbalkan We have raised the priority of this since it was first reported. Doing this site-wide will take some time though. It is a priority in my current sprint.

ping @jsouth We should talk about this tomorrow.

**Comment by pmario** [comment]
imo seems to be fixed. so I'll close
