### ISSUE TITLE
toomanyrequests: too many failed login attempts for username or IP address

### ISSUE THREAD

**Issue by ninjrok** [docker/hub-feedback#1250]
I'm getting the same error for 2 weeks and yes, I am using the right username/password now. 
https://github.com/docker/hub-feedback/issues/786 says the issue should resolve itself in a couple of hours, but...

And https://github.com/docker/hub-feedback/issues/814 is useless.

Any help is appreciated.

Docker version 17.06.2-ce, build cec0b72 on Ubuntu 16.04

**Comment by FortisFortuna** [comment]
Is there intentional rate limiting? If so, can I just pay somewhere to remove the limit?

**Comment by FortisFortuna** [comment]
We fixed this by removing the $ characters in our password.

**Comment by sara-02** [comment]
@ninjrok It worked after a few retries for me, not sure what helped. But in my `.docker/config.json`  the url was pointing to `https://index.docker.io/v1/` and I saw that in error, it was trying to hit `Error response from daemon: Get https://registry-1.docker.io/v2/`. So I updated the config.json and changed the version to v2 and tried logging in again, and it worked. It also created a new auth token for me, w.r.t v2 and appended that to the config.json

**Comment by nandanrao** [comment]
Warning: 

I had the same issue, only it happened AFTER I changed my password. I then tried to change AGAIN via the web login, as per the above suggestion, and now I get "Too many login attempts" from the web login and can't login anywhere.

**Comment by nazar-pc** [comment]
I deleted the whole `.docker` directory and tried `docker login` again, finally worked for me.

**Comment by karser** [comment]
The idea of @nazar-pc worked for me but **don't remove `.docker` folder** because other important stuff can be there, docker-machine certificates for example.
This is safer:
```
rm ~/.docker/config.json
docker login
```

**Comment by robertpro** [comment]
I had to use my phone's data in order to login, then go back to my wifi network in order to push the image

**Comment by Mavwarf** [comment]
> We fixed this by removing the $ characters in our password.

Same here! I could not run my stuff on my MacBook using MiniKube. Failed to pull images from docker hub all the time. After I changed the docker hub PWD to a new one without $ is worked immediately! Thanks a lot for saving my time :-)

**Comment by riskiana** [comment]
"Error response from daemon: Get https://registry-1.docker.io/v2/: toomanyrequests: too many failed login attempts for username or IP address"

error above also happened to me when I tried to login to dockerhub. there was https://index.docker.io/v1/ stored at windows credential manager. After removing it and relogin, I works

**Comment by yachtcaptain23** [comment]
I had to quit out of the VPN I was using and was able to sign-in successfully.

**Comment by axeluhl** [comment]
Same here. A ampersand character in the password will not let me log in. WTF??? Changing the PW to something without any special characters makes it work again. How backward is this?

**Comment by missinglink** [comment]
:+1: same here on a Mac pasting into an `Iterm2` console window.
once I changed the password to not contain a `$` it worked fine.
I also tried escaping the `$` without success.

The error message here is a bit cryptic, I wouldn't have guessed it meant the password was wrong 🤷

**Comment by MateuszGalasinski** [comment]
Had the same problem, no VPN, deleted credentials from windows manager and reset my password on dockerhub to make sure. Still couldn't login from cli.
But I found it's possible to generate access token on dockerhub webpage and used it instead of password successfully

**Comment by sanga04** [comment]
Had same problem, fixed by logging in docker GUI. really helps try.

**Comment by Guigehling** [comment]
> @ninjrok It worked after a few retries for me, not sure what helped. But in my `.docker/config.json` the url was pointing to `https://index.docker.io/v1/` and I saw that in error, it was trying to hit `Error response from daemon: Get https://registry-1.docker.io/v2/`. So I updated the config.json and changed the version to v2 and tried logging in again, and it worked. It also created a new auth token for me, w.r.t v2 and appended that to the config.json, while keeping the v1 auth intact, and changing the version for it back to v1.
> so now my config.json looks something like
> 
> ```
> {
> 	"auths": {
> 		"https://index.docker.io/v1/": {
> 			"auth": "blah-blah"
> 		},
> 		"https://index.docker.io/v2/": {
> 			"auth": "blah-blah-blah"
> 		}
> 	}
> }
> ```


I based it on your example and left the .docker.config.josn file like this, withou the auth

`	"auths": {
		"https://index.docker.io/v1/": {},
		"https://index.docker.io/v2/": {}
	},
`

It worked!

**Comment by mariamihai** [comment]
Years later,  and this is still an issue...

The only solution form me was [this](https://forums.docker.com/t/too-many-failed-login-attempts/7502/11) comment.

This is extremely frustrating.

**Comment by merc-angel** [comment]
> 
> 
> Years later, and this is still an issue...
> 
> The only solution for me was [this](https://forums.docker.com/t/too-many-failed-login-attempts/7502/11) comment. Had to manually logout from hub.docker.com.
> 
> This is extremely frustrating.

Yes, but it is a protection against attacks such as brute force, etc. Problem was solved by myself by deleted 
1. Logout from all terminals
2. Logout from Docker Desktop.
3. rm ~/.docker/config.json
4. Login from Docker Desktop
5. **Login from terminal works in the end**...

**Comment by stevemarksd** [comment]
I tried to push from the UI and it worked... 

![image](https://user-images.githubusercontent.com/58653359/97606393-b2869a80-1a4a-11eb-99fa-62d064dcaad3.png)

**Comment by UzairKhurshid** [comment]
in my case i changed my docker hub password.
run your cmd as administrator and try login again
this worked for me

**Comment by m4yer** [comment]
Nothing above worked for me, even deleting .docker/config.json didn't solve the problem.
But what worked for me is the following (execute in terminal):
`docker logout`
then again
`docker login`
Then it works.

**Comment by saad569** [comment]
We fixed this by removing the $  OR * characters in my password.

**Comment by missinglink** [comment]
`removestale`

As per my comment https://github.com/docker/hub-feedback/issues/1250#issuecomment-618476336

The solution is to fix the encoding issue and the interim fix is to improve the error message.

**Comment by lschirmbrand** [comment]
Ran into the same problem and all the solution above didn't work for me.

What worked for me, in the end, was to create a new token and use it instead of the password.
A token you can create on Docker Hub in your Account-Settings.

**Comment by Michael-Fletcher** [comment]
It's a software bug in Docker.  It's caching information locally.  I had to do a number of things to fix it. 
Create an access token on docker.com and use that. 
Do a docker logout. Sometimes you may even need to do a systemctl restart docker or login with another users account/network.  Unfortunately there is no option on dockerhub to whitelist an IP address, which is surprising considering it knows your IP well enough to blacklist it.

**Comment by cruzzoe** [comment]
I ran the cmd rm ~/.docker/config.json from @karser however this still didnt work in my case. 

I then ran docker logout which gives:

`Removing login credentials for https://index.docker.io/v1/`

Then docker login worked nicely.

**Comment by Jeffr-K** [comment]
In my case, I resolve that issue with re-authentication. I sign out in docker desktop, then re-login.

**Comment by bounlu** [comment]
I have the same issue.

However, I don't have the option to reset the password or logout-relogin or update the config.json file to solve the issue.

Because I am using an AMI on AWS with Nextflow to pull private images from Docker Hub. Any change on AMI will change the AMI ID, which will break everything on AWS Batch, job queues, compute environments, launch templates etc. Everything has to be recreated if AMI ID is updated, which is not feasible in case of having many resources. And AWS does not allow to update AMI in place by keeping the AMI ID same.

How to solve the Docker Hub issue in my case?

**Comment by Afrokk** [comment]
Here's how I resolved this issue without changing the password:

- Removed the Docker config: `rm -rf ~/.docker/config.json`
- Logged out from multiple Docker registry servers:
  - `docker logout [registry-1.docker.io](http://registry-1.docker.io/)`
  - `docker logout [hub.docker.com](http://hub.docker.com/)`
  - `docker logout [index.docker.io](http://index.docker.io/)`
-  Then I was able to log in again normally using:
    - `docker login`
