### ISSUE TITLE
No github link for source project

### ISSUE THREAD

**Issue by darkmattercoder** [docker/hub-feedback#1732]
I recently set up a new project: https://hub.docker.com/r/darkmattercoder/qt-build
I cannot see a link to the github repository below the owner part:

![image](https://user-images.githubusercontent.com/2217280/50730799-3379f100-1156-11e9-90b7-5bdce972e7d9.png)

I set up automated builds within the repository and the builds are passing successfully. One thing to mention: I disabled both build and push by providing hooks for it in my github repo, causing the automated build only fetching the readme from github.

**Comment by spencerhcheng** [comment]
in progress: https://github.com/docker/mercury-ui/tree/sc-2291

**Comment by thaJeztah** [comment]
@spencerhcheng that's linking to a private repository :sweat_smile:

**Comment by gitfool** [comment]
@thaJeztah I'm using Azure Pipelines for the automated build. The `Dockerfile` tab on Docker Hub showing the Dockerfile source and a link to the GitHub `Source Repository` is still really useful and desired.

I tried configuring GitHub integration and disabling the Docker Hub automated build for [dockfool/cake-docker](https://hub.docker.com/r/dockfool/cake-docker), but I don't get a `Dockerfile` tab. Is it possible to get this feature but without using Docker Hub for automated builds?

**Comment by darkmattercoder** [comment]
@gitfool Probably you should open a corresponding issue separate from this one to keep better track of it. This issue here is not about a missing Docker file tab.

Probably you better post your suggestion in the better fitting issue #1735, or open a separate one.

**Comment by qhh0205** [comment]
Same here, how to display Dockerfile tab and github link?

**Comment by meticulous-dft** [comment]
Should be fixed.

**Comment by gitfool** [comment]
@meticulous-dft I now see the `Dockerfile` tab but it says “No Dockerfile available”.

**Comment by darkmattercoder** [comment]
@meticulous-dft please re-open, because it is not yet fixed. The repo link is now only visible if u am logged in. When I am not logged in, then there is only a message that asks for login
