### ISSUE TITLE
Autobuild webhook on Bitbucket throws error 400 missing field 'username'

### ISSUE THREAD

**Issue by Juanpam** [docker/hub-feedback#1825]
## Problem description
When configuring a repo to make use of the autobuild features and testing with a push to the bitbucket repo, the webhook response status is 400 and the body is:

`{
  "error": "Required field 'username' is missing"
}`

According to https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html this fields are being deprecated from the Bitbucket API so docker hub may have to update their API in order to work.

Manually building the images work though, but it would be very nice to recover the autobuild feature!

I'm attaching an screenshot of the request response:

![Screen Shot 2019-05-31 at 2 43 08 PM](https://user-images.githubusercontent.com/8345151/58730850-d73c9580-83b2-11e9-8e11-5f9fc6e941be.png)

**Comment by gmitre** [comment]
+1

**Comment by xuezhma** [comment]
+1

We have been having this issue since PST 1:03 am today (May 31).

**Comment by xuezhma** [comment]
https://registry.hub.docker.com/hooks/bitbucket is working for us.
https://cloud.docker.com/api/build/v1/vcs/foo/trigger/call/ is not

they are using the same post body

**Comment by sarkis** [comment]
Thank you for the report, this issue has been fixed.

**Comment by cowsrule** [comment]
If you continue to see any problems here please re-open the ticket.

**Comment by xuezhma** [comment]
![Screen Shot 2019-05-31 at 4 34 42 PM](https://user-images.githubusercontent.com/14795799/58739941-2807ba80-83c2-11e9-951e-e9e65dd11276.png)

tried pushing a new tag just now. still not working

**Comment by sarkis** [comment]
@xuezhma please try to trigger again. This should now be resolved. Please let us know here if you continue to experience issues.

**Comment by Time6628** [comment]
We were getting this error, we are now getting:
```
{"error": "Branch 'dev/master' not found"}
```

**Comment by sarkis** [comment]
@Time6628 I tried to reproduce this by creating a `dev/master` branch and then adjusting my Automated Build on docker hub to track this branch as the build rule and was able to successfully push to the repo and trigger auto builds. Given the above and based on the change set that was required to fix this issue (#1825), the issue you are seeing with branches is likely unrelated. If you continue to experience issues after confirming the Build Rules are correct, please open a new issue on this github repo with as much info as you can provide.
