### ISSUE TITLE
Docker Hub autobuild error emails provide broken link

### ISSUE THREAD

**Issue by mbentley** [docker/hub-feedback#1957]
## Problem description
If you have an autobuild that fails and you have notifications enabled, you will receive an email like this:

<img width="609" alt="screenshot 2020-02-29 at 6 34 53 AM" src="https://user-images.githubusercontent.com/414445/75606722-a0b8b600-5abd-11ea-941e-cfdb5afe851b.png">

The link in the "Click here for more information."  is https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/81fa8848-ead5-4e7f-9fcd-73aac706534c/ but that takes me to a 404.  I thought at first it might be because I wasn't logged in but I am logged in to Hub just fine and it always returns a 404.

**Comment by FozzeY** [comment]
There are a few more reports on this bug: #1980, #1985.
I am currently experiencing the same issue on a PR Status Check as well. Is there a workaround for it, perhaps some tweaks to the URL? Seems like the API v1 deprecation is the root cause.

**Comment by binhex** [comment]
Yep this is another annoyance with docker Hub +1 from me.

**Comment by nevrending** [comment]
Hi @manishtomar , any updates on this one?

**Comment by nevrending** [comment]
Hi @thaJeztah , any updates?

**Comment by thaJeztah** [comment]
I think @arkodg looked into this one and, while we understand what's causing it, fixing it required some larger changes that were not possible to make in the short term.

**Comment by arkodg** [comment]
@mbentley @nevrending @FozzeY @binhex sorry it took a while for us to spend cycles on this issue
The issue should be resolved now

**Comment by thaJeztah** [comment]
Let me go ahead and close this ticket, but feel free to continue the conversation if the issue is not resolved

**Comment by shams858** [comment]
I'm still experiencing the issue with the following link.

https://hub.docker.com/login/?next=/redirect/%3Fresource_uri%3D/api/audit/v1/action/8703e1d9-e6dc-46e1-b6bb-7869f1d739b6/

**Comment by emmahyde** [comment]
Still seeing this occur as well!

**Comment by oerp-odoo** [comment]
Still experiencing this issue. On github, status links to docker hub are broken. Is it really that hard to fix? Seems like an old bug.

**Comment by etheleon** [comment]
still @manishtomar seeing this on github's PR
