### ISSUE TITLE
Docker Hub does not show image information for tag

### ISSUE THREAD

**Issue by andreaangiolillo** [docker/hub-feedback#2369]
## Problem description

Occasionally, when uploading a docker image tagged with `latest`, `v1.14.3`, and `v1.14.3-2024-02-13,` some tags fail to display Digest, OS, and Layer details. However, `docker buildx imagetools inspect` consistently reveals the accurate image information.

```
docker buildx imagetools inspect  mongodb/atlas:latest                                                                                              
Name:      docker.io/mongodb/atlas:latest
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:c55a8ea2f32e8a4dafc651aefc71bb869a3a2afd814463db802e386a4c48b7e5

Manifests:
  Name:        docker.io/mongodb/atlas:latest@sha256:00ea4fc7f19a33935c648209e251dba8aa0901729f91b3fb39f9325a7653e4c6
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/amd64

  Name:        docker.io/mongodb/atlas:latest@sha256:eac1c76ae35802162190c85197ff0003dfe1562f8765502fb42cd952faa1c0a0
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    linux/arm64

  Name:        docker.io/mongodb/atlas:latest@sha256:3c9991de32fa8fd6fb2be7ec247540b8fbe19a59a47720fa12170870e5c12ac8
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations:
    vnd.docker.reference.digest: sha256:00ea4fc7f19a33935c648209e251dba8aa0901729f91b3fb39f9325a7653e4c6
    vnd.docker.reference.type:   attestation-manifest

  Name:        docker.io/mongodb/atlas:latest@sha256:3bc995d63c031db4e506c893c24ac94577661c5b10c1ea96424c9c97cb2ae1a5
  MediaType:   application/vnd.oci.image.manifest.v1+json
  Platform:    unknown/unknown
  Annotations:
    vnd.docker.reference.digest: sha256:eac1c76ae35802162190c85197ff0003dfe1562f8765502fb42cd952faa1c0a0
```

We push the docker image to the `mongo/apix` from a staging docker hub repo via `docker builds imagetools create`

```bash
  docker buildx imagetools create \
    --tag ${{ env.IMAGE_REPOSITORY }}:latest \
    --tag ${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }} \
    --tag ${{ env.IMAGE_REPOSITORY }}:${{ env.LATEST_VERSION }}-${{ env.DATE }} \
    ${{ env.STAGING_IMAGE_REPOSITORY }}:latest
```

## Debug Information
**Browser name and version**:
Google Chrome Version 121.0.6167.160

**URL**:
https://hub.docker.com/repository/docker/mongodb/atlas/tags?page=1&ordering=last_updated

**Timetamp or time range**: 
GMT

**Public IP**: 

**Hub Username**:
[svcdockerhubapix429](https://hub.docker.com/u/svcdockerhubapix429)

## Screenshots of the issue (if applicable)
![Screenshot 2024-02-13 at 10 11 03](https://github.com/docker/hub-feedback/assets/5663078/50d7c8c7-1ae8-4901-8987-d24810353f24)

![Screenshot 2024-02-13 at 10 19 38](https://github.com/docker/hub-feedback/assets/5663078/957771ce-a71d-4942-94db-c0b168647eeb)

# Task List
- [x] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [x] I have looked through other issues and they do **NOT** apply to me

**Comment by stepheUp** [comment]
Hello, thank you for reporting, we'll look into it

**Comment by nephatrine** [comment]
I am also experiencing this same issue.

**Comment by stepheUp** [comment]
Hello thank you very much for reporting, we are working on this but we were unable to reproduce the issue for now. If you could share more examples of running into this, it would be highly appreciated.
Thank you very much for your help

**Comment by nephatrine** [comment]
> If you could share more examples of running into this, it would be highly appreciated.

I push these tags with a single imagetools create command:
- nephatrine/nginx-ssl:latest
- nephatrine/nginx-ssl:1.25.4
- nephatrine/nginx-ssl:1.25
- nephatrine/nginx-ssl:1

All of the tags show all five platforms/digests I compile for in the tag information... except for `nephatrine/nginx-ssl:1.25.4` - that one only shows `linux/386` and none of the others. If I try to pull it or use imagetools inspect, I can get those other architectures just fine - so they're clearly there but dockerhub just doesn't show them as existing.

**Comment by stepheUp** [comment]
Hello nephatrine, that is helping thanks a lot

**Comment by nephatrine** [comment]
I'd like to note for anyone else that comes across this that pushing each architecture to dockerhub as a separate image and then using manifest create and manifest push does not have this issue and so is a workaround for now if you don't mind having a ton of extra tags show up (i.e. `latest-amd64`, `latest-arm64`, etc. in addition to just `latest`).

**Comment by stepheUp** [comment]
We have some rework planned on another topic which will also fix this issue, so it's planned to be fixed in the coming months but i don't have any visibility on the release date. Stay tuned.

**Comment by alexandrecuer** [comment]
same problem here, with the following images, built through github actions : 
- alexjunk/emoncms:alpine3.19_emoncms11.5.0
- alexjunk/emoncms:11.5.0_AL3.19
- alexjunk/emoncms:alpine3.19_emoncms11.5.0_1

![image](https://github.com/docker/hub-feedback/assets/24553739/4c917c68-c0c8-4811-8074-421ad33b59a7)

with another profile, the same github actions produced an image which is correctly described in the hub :

![image](https://github.com/docker/hub-feedback/assets/24553739/717e4c83-bd0f-42fc-ab90-ad1d13cf4c2f)

**Comment by sheltongraves** [comment]
This issue has been fixed. Please let us know if this happens again.

**Comment by jhesketh** [comment]
Hello,

We are still seeing this issue on a few of our repositories. Each of these tags should have multiple architectures (which I can check with inspect): https://hub.docker.com/r/grafana/enterprise-metrics/tags but some are missing:

![image](https://github.com/docker/hub-feedback/assets/728450/ff6b8913-7ab6-4ac9-a24e-81e160be0d32)

**Comment by robiningelbrecht** [comment]
I'm having the same issue for the repository https://hub.docker.com/repository/docker/robiningelbrecht/strava-statistics/tags
I'm using Github actions to create and publish new tags, even though the tags are pushed successfully and you can pull new tags, they don't show up on docker hub.

For example `docker pull robiningelbrecht/strava-statistics:v2.4.2`
