### ISSUE TITLE
Cannot change my password

### ISSUE THREAD

**Issue by RalfComtesse** [docker/hub-feedback#2399]
## `docker info` output

Docker Info:
```yaml

```

## Debug Information
**Browser name and version**:

**URL**:

**Timetamp or time range**: 

**Public IP**: 

**Hub Username**:

## Screenshots of the issue (if applicable)

# Task List
- [ ] This is **NOT** a security issue
- [ ] I do **NOT** have a Docker subscription
- [ ] I have looked through other issues and they do **NOT** apply to me

**Comment by hugoivankm** [comment]
### Problem description
Unable to change my password on docker hub. When I click on the option to change password I can see a Red box with the text " There was an error try again later"

###Docker info
N/A

### Debug Information
Browser name and version:
Firefox 127.0.2 and  Chromium 126.0.6478.126 

**URL:** https://hub.docker.com/settings/general

**Timetamp or time range:**  2:26 AM Wednesday, July 10, 2024 UTC time

Public IP: :D

**Hub Username:** hugoivankm



### Error messages (on screen or in browser console)
In the browser console I can see a couple of CORS errors

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.docker.com/dbconnections/change_password. (Reason: header ‘x-docker-api-client’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.docker.com/dbconnections/change_password. (Reason: CORS request did not succeed). Status code: (null).

**Comment by oerp-odoo** [comment]
Any update on this? Can't use docker hub at all now, because can't login via `docker login` command..

**Comment by zarif98** [comment]
Same issue here. Unable to change my password and deploy my build on GitHub actions. Someone, please take a look at this.

**Comment by bit-shifted** [comment]
Has any more info come out of this? Completely locked out and unable to reset my password.

**Comment by bit-shifted** [comment]
Has any more info come out of this? Completely locked out of my account and cannot reset my password.

**Comment by hugoivankm** [comment]
Update, it looks like the issue is fixed. I tested it and it looks to be up and running.

**Comment by ghudgens** [comment]
This is not fixed.  I am still unable to reset my password...

**Comment by bastiao** [comment]
same problem here!

**Comment by imkozin** [comment]
Password reset isn't working

**Comment by Ankitchandre** [comment]
i am facing the same issue , password reset page isnt working

**Comment by ivie07** [comment]
same here.. docker login hanged-up..
password reset not working..

**Comment by Siddhant-** [comment]
<img width="423" alt="Image" src="https://github.com/user-attachments/assets/a25dee75-931f-4d77-9396-251f6e2be578" />

**Comment by andher050404** [comment]
same here

**Comment by benjsmi** [comment]
Yup. Same here.

**Comment by technicallyjosh** [comment]
👋🏼 We have made quite a few changes to emails and stability around this recently. If this is still an issue, it would be suggested to reach out to our support team as it would be a better place to share your email to look into.
