### ISSUE TITLE
Activate Autobuild setting being ignored

### ISSUE THREAD

**Issue by nigelpoulton** [docker/hub-feedback#338]
When creating a new Automated Build repo on Docker Hub, the `When Active, new pushes will trigger automatic builds` is not passed through to the repo upon creation.

In the image below the checkbox is un-checked/disabled 

![hub-image-1](https://cloud.githubusercontent.com/assets/10812787/9746354/6e28c718-566f-11e5-9337-40d50955f997.png)

But when the repo is created, the Build Settings tab shows it as checked/enabled.

![hub-image-2](https://cloud.githubusercontent.com/assets/10812787/9746386/9569c55c-566f-11e5-8b69-c9939b9f7703.png)

I've checked this with FireFox and Chrome. Hub username: nigelpoulton

**Comment by nhsiehgit** [comment]
Yup this should be fixed.

@nigelpoulton can you confirm - when you uncheck the activate auto-build in the settings page that it does in fact deactivate?

Should also double check to see if all new autobuilds are defaulting to activated or not.

marking as bug and triaging

**Comment by nigelpoulton** [comment]
Yes, I can confirm that when I uncheck the activate auto-build in the settings page is does in fact deactivate.

I can also confirm that when I uncheck during repo creation, it still shows as checked in the actual repo and it does autobuild when I push to Github.

So it appears that from within the repo (after its been created) the option works correctly.  The issue appears to be that the setting chosen when creating the repo is not captured and passed to the repo on creation.

Hope that helps.
