### ISSUE TITLE
setcap 'cap_net_bind_service=+ep' /path/to/binary/executable has started to fail builds

### ISSUE THREAD

**Issue by Karm** [docker/hub-feedback#444]
Dear DockerHub fellows,

this [Dockerfile](https://github.com/intfeed/sinkit-resolver/blob/testing/Dockerfile) builds just fine on my system, `docker-io-1.5.0-1.fc20.x86_64`, although it fails as an automated build on [DockerHub](https://hub.docker.com/r/karm/sinkit-resolver/tags/) with the undermentioned error (see the bottom of the log snippet).

It is noteworthy that the same command was passing just fine some 20 hours ago.

``````
```
Complete!
Cleaning repos: fedora updates
Cleaning up Everything
 ---&gt; 96b4a03a89ec
Removing intermediate container 359270ecf326
Step 7 : RUN useradd -s /sbin/nologin sinkit
 ---&gt; Running in ca99f3a05fb5
 ---&gt; c1bcf3f599b8
Removing intermediate container ca99f3a05fb5
Step 8 : USER sinkit
 ---&gt; Running in c0031bc231ef
 ---&gt; 04fc366143d3
Removing intermediate container c0031bc231ef
Step 9 : RUN go get ${GODNS_REPO} &amp;&amp;     echo "Got GoDNS." &amp;&amp;     cd ${GOPATH}/src/${GODNS_REPO}/ &amp;&amp;     git checkout ${GODNS_TAG} &amp;&amp;     echo "Switched to tag ${GODNS_TAG}." &amp;&amp;     go build &amp;&amp;     echo "Built GoDNS." &amp;&amp;     cp godns /home/sinkit/ &amp;&amp;     ls -lah ./ &amp;&amp;     cd /home/sinkit/ &amp;&amp;     ls -lah ./ &amp;&amp;     rm -rf ${GOPATH}
 ---&gt; Running in 29be660b7e36
Got GoDNS.
[91mSwitched to a new branch 'fallback'
[0mBranch fallback set up to track remote branch fallback from origin.
Switched to tag fallback.
Built GoDNS.
total 9.2M
drwxr-xr-x 3 sinkit sinkit 4.0K Nov  7 21:16 .
drwxr-xr-x 3 sinkit sinkit 4.0K Nov  7 21:16 ..
drwxr-xr-x 8 sinkit sinkit 4.0K Nov  7 21:16 .git
-rw-r--r-- 1 sinkit sinkit   28 Nov  7 21:16 .gitignore
-rw-r--r-- 1 sinkit sinkit 1.1K Nov  7 21:16 LICENSE
-rw-r--r-- 1 sinkit sinkit 3.2K Nov  7 21:16 README.md
-rw-r--r-- 1 sinkit sinkit 2.6K Nov  7 21:16 cache.go
-rwxr-xr-x 1 sinkit sinkit 9.1M Nov  7 21:16 godns
-rw-r--r-- 1 sinkit sinkit 1.3K Nov  7 21:16 godns.conf
-rw-r--r-- 1 sinkit sinkit  334 Nov  7 21:16 godns_test.go
-rw-r--r-- 1 sinkit sinkit 4.4K Nov  7 21:16 handler.go
-rw-r--r-- 1 sinkit sinkit 2.8K Nov  7 21:16 hosts.go
-rw-r--r-- 1 sinkit sinkit  853 Nov  7 21:16 hosts_test.go
-rw-r--r-- 1 sinkit sinkit 1.4K Nov  7 21:16 main.go
-rw-r--r-- 1 sinkit sinkit 9.8K Nov  7 21:16 resolver.go
-rw-r--r-- 1 sinkit sinkit  689 Nov  7 21:16 rob_test.go
-rw-r--r-- 1 sinkit sinkit 1.1K Nov  7 21:16 server.go
-rw-r--r-- 1 sinkit sinkit 1.8K Nov  7 21:16 settings.go
total 9.1M
drwx------ 4 sinkit sinkit 4.0K Nov  7 21:16 .
drwxr-xr-x 4 root   root   4.0K Nov  7 21:16 ..
-rw-r--r-- 1 sinkit sinkit   18 Aug 18 13:37 .bash_logout
-rw-r--r-- 1 sinkit sinkit  193 Aug 18 13:37 .bash_profile
-rw-r--r-- 1 sinkit sinkit  231 Aug 18 13:37 .bashrc
drwxr----- 3 sinkit sinkit 4.0K Nov  7 21:16 .pki
drwxr-xr-x 5 sinkit sinkit 4.0K Nov  7 21:16 go
-rwxr-xr-x 1 sinkit sinkit 9.1M Nov  7 21:16 godns
 ---&gt; 8890f79b1d43
Removing intermediate container 29be660b7e36
Step 10 : ADD godns.conf /home/sinkit/godns.conf
 ---&gt; a9f20430080c
Removing intermediate container 50499059c5e5
Step 11 : USER root
 ---&gt; Running in 2207f78df925
 ---&gt; ebe8ae50d170
Removing intermediate container 2207f78df925
Step 12 : RUN ls -lah /home/sinkit/
 ---&gt; Running in e9b293bd3ce4
total 9.1M
drwx------ 3 sinkit sinkit 4.0K Nov  7 21:16 .
drwxr-xr-x 5 root   root   4.0K Nov  7 21:16 ..
-rw-r--r-- 1 sinkit sinkit   18 Aug 18 13:37 .bash_logout
-rw-r--r-- 1 sinkit sinkit  193 Aug 18 13:37 .bash_profile
-rw-r--r-- 1 sinkit sinkit  231 Aug 18 13:37 .bashrc
drwxr----- 3 sinkit sinkit 4.0K Nov  7 21:16 .pki
-rwxr-xr-x 1 sinkit sinkit 9.1M Nov  7 21:16 godns
-rw-r--r-- 1 root   root   1.3K Nov  7 21:13 godns.conf
 ---&gt; 904403bd2db8
Removing intermediate container e9b293bd3ce4
Step 13 : RUN setcap 'cap_net_bind_service=+ep' /home/sinkit/godns
 ---&gt; Running in 6a09e746d0bf
[91mFailed to set capabilities on file `/home/sinkit/godns' (Invalid argument)
[0m[91musage: setcap [-q] [-v] (-r|-|&lt;caps&gt;) &lt;filename&gt; [ ... (-r|-|&lt;capsN&gt;) &lt;filenameN&gt; ]

 Note &lt;filename&gt; must be a regular (non-symlink) file.
[0mRemoving intermediate container 6a09e746d0bf
{"status":"The push refers to a repository [registry-1.docker.io/karm/sinkit-resolver] (len: 1)"}

{"errorDetail":{"message":"Repository does not exist: registry-1.docker.io/karm/sinkit-resolver"},"error":"Repository does not exist: registry-1.docker.io/karm/sinkit-resolver"}
```
``````

 There is no problem with setting `setcap` on that godns binary on my system: `Step 12 : RUN setcap 'cap_net_bind_service=+ep' /home/sinkit/godns` passes just fine.

Last but not least, what is it with that `Repository does not exist` error?

Thank you very much for your time and comments.
Cheers
Michal Karm Babacek

**Comment by GrahamDumpleton** [comment]
Encountering similar issue:

```
[91m+ setcap cap_net_bind_service=+ep /usr/local/apache/bin/httpd
[0m[91mFailed to set capabilities on file `/usr/local/apache/bin/httpd' (Invalid argument)
[0m[91mThe value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```

Automated builds now totally unusable and can no longer make updates.

**Comment by bcwalrus** [comment]
That should've been fixed by now. Some repositories still residing on the v1 registry had some auth issues. Sorry about that. Ping me if it's still bad.

**Comment by GrahamDumpleton** [comment]
Nope. Still occurring.

Build details for latest failure is:

```
Cloning into 'bhkwjj5ernemmqxdaaxxbgd'...
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: f4bf5c7
Arch: amd64
GoVersion: go1.4.2
```

**Comment by GrahamDumpleton** [comment]
@bcwalrus The setcap problem still persists for me.

**Comment by GrahamDumpleton** [comment]
For me at least, Docker Hub appears to have fixed the problem a few days after the last update.

**Comment by GrahamDumpleton** [comment]
FWIW. Builds broke once again and Docker Hub automated builds are now totally useless if using setcap, with it being broken for a number of weeks.

**Comment by bryanlatten** [comment]
+1  i'm also seeing the exact same issue

**Comment by jcberthon** [comment]
I have the same error trying to set capabilities on ntpd on a Ubuntu 16.04 based container. The Dockerfile build shows:

```
Step 1/6 : FROM ubuntu:16.04
 ---> f49eec89601e
Step 2/6 : RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ntp     && apt-get clean -q     && rm -Rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 471bb14fcf41
Step 3/6 : RUN setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep' /usr/sbin/ntpd
 ---> Running in 8f9ea5657e84
Failed to set capabilities on file `/usr/sbin/ntpd' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
The command '/bin/sh -c setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+eip' /usr/sbin/ntpd' returned a non-zero code: 1
```

However, executing the command `setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep' /usr/sbin/ntpd` on the host works fine. And the file `/usr/sbin/ntpd` inside the container image is a regular binary file, no symlink.

Note: the host (x86_64) is running Ubuntu 16.04 as well and the host /usr/sbin/ntpd binary is on a BTRFS filesystem. Docker is configured to use BTRFS as storage backend. I'm running Docker 1.13.0.

**Comment by jcberthon** [comment]
I have just tested the same Dockerfile (only the base image has changed from `ubuntu:16.04` to `armhf/ubuntu:16.04`) on another host running Raspbian and Docker 1.13.0 (ARM 32bit) but using the overlayfs2 storage backend (on top an ext4 partition).

Step 3 (`Step 3/6 : RUN setcap 'cap_net_bind_service,cap_sys_time,cap_sys_resource,cap_sys_nice+ep' /usr/sbin/ntpd`) is successful!

So the problem is with Docker storage backend, at least the BTRFS storage backend (maybe other) does not support setting capabilities on a regular file.
