### ISSUE TITLE
After a build that terminates in an error or exception no information is available

### ISSUE THREAD

**Issue by interactiveblueprints** [docker/hub-feedback#455]
When an automatic build or a triggered build halts with an error or exception going to the build page (https://hub.docker.com/r/<user>/<repo>/builds/<buildnumber>/) gives a page without any information (all boxes like Dockerfile, Build Code, README, etc. are empty).

FF (42 and developer edition (44)) on Linux.

I see a lot of these errors in the console: "Strict-Transport-Security: The site specified a header that could not be parsed successfully." Even for for example https://hub.docker.com/public/styles/font-awesome.min.css

**Comment by maport** [comment]
I'm not sure if this is just restricted to builds that result in an error: My last three builds all bring up build detail pages with no information. The first and last one have a status of "error" but the second one has a status of "done":

https://hub.docker.com/r/codesimple/elm/builds/bbbpzdnonww2xnhbqycjcv8/
https://hub.docker.com/r/codesimple/elm/builds/btjyu2rrwaly83nxsg3ckem/
https://hub.docker.com/r/codesimple/elm/builds/bwxtwpxf87ft5jyb8sszvjc/

**Comment by binhex** [comment]
yep add me to this list, no output shown and just a "done" build status
https://hub.docker.com/r/binhex/arch-base/builds/bg72vvxmestpbjurzlnmeij/

**Comment by frodopwns** [comment]
I tried to build a "working" dockerfile yesterday roughly 5 times.  All failed and provided no information.  Then today I rerun the build and it says "done" but still no details shown.

https://hub.docker.com/r/drud/jenkins/builds/

Private repo but I can make details available if needed.

**Comment by shift** [comment]
Same situation here on a private container.

Build status: "exception", output NULL, https://hub.docker.com/r/chartmogul/platform/builds/bumchx3bwqmhi8xsyzccwsk/

**Comment by jakirkham** [comment]
Sounds similar to this error ( https://github.com/docker/hub-feedback/issues/417 ). Maybe only how the error appears has changed.

**Comment by ChristopherBiscardi** [comment]
@interactiveblueprints 

> https://hub.docker.com/r///builds//

That looks like a bug in how you were routed to the builds page. Can you yield any additional information (browser, setup, etc)


----

The "empty build page" issue is a bug which is currently being investigated. The logs are not being returned to the UI, resulting in an empty object which the UI faithfully tries to display.

**Comment by mghazizadeh** [comment]
We released a fix last night that should address the logs not showing up in most, if not all cases. Please let us know if this is not the case. When I click on the links above now, it seems the logs are back. Apologies for the inconvenience.

**Comment by maport** [comment]
@mghazizadeh Thanks, all working again for me.

**Comment by jakirkham** [comment]
Still seeing this particular with builds that have git submodules https://github.com/docker/hub-feedback/issues/449

**Comment by jakirkham** [comment]
Here's an example of a normal build with this issue ( https://hub.docker.com/r/nanshe/nanshe/builds/bqqw6sb5sixqnyqxgzljdsb/ ). Screenshot below.

<img width="1554" alt="screen shot 2015-11-15 at 0 17 39" src="https://cloud.githubusercontent.com/assets/3019665/11167385/530f1f38-8b2e-11e5-8766-8a6de681b8ed.png">
