### ISSUE TITLE
Vague "Authentication is required" on public and private automated builds

### ISSUE THREAD

**Issue by oryband** [docker/hub-feedback#465]
Our public [rounds/10m-python](https://hub.docker.com/r/rounds/10m-python) automated-build just stopped working today. Some other private builds as well. All fail with the same error:
```
Cloning into 'bzfmynbzjuwxvszv5ykquz3'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: f4bf5c7
Arch: amd64
GoVersion: go1.4.2
Step 0 : FROM rounds/10m-python
Authentication is required.
```
That IP up there is [github](https://github.com) I think.

What does "Authentication is required" mean? This is a public automated build, from a public GitHub repo: [rounds/10m-docker-images](https://github.com/rounds/10m-docker-images) in the `python/` dir, no authentication is required at all.

**All our automated builds are suddenly failing like this.**

**Comment by oryband** [comment]
@rounds/server

**Comment by doodyparizada** [comment]
:+1:

**Comment by gadisr** [comment]
:+1:

**Comment by koenbollen** [comment]
I've got the same issue:
```
Cloning into 'redacted'...
Warning: Permanently added the RSA host key for IP address '1.2.3.4' to the list of known hosts.
KernelVersion: 3.13.0-40-generic
Os: linux
BuildTime: Mon Oct 12 05:37:18 UTC 2015
ApiVersion: 1.20
Version: 1.8.3
GitCommit: 123456
Arch: amd64
GoVersion: go1.4.2
Step 0 : FROM ruby:2.2-onbuild
Authentication is required.
```

**Comment by liorama** [comment]
Got the same issue, this is a real problem hindering system wide deployment.

**Comment by avivl** [comment]
:+1:

**Comment by mitar** [comment]
+1

**Comment by jewilmeer** [comment]
:+1:

**Comment by oryband** [comment]
I just want to emphasize that this practically means **dockerhub.com doens't work**, as all our production images use automated builds and are **failing the same way**.

**Comment by robinvw1** [comment]
:+1:

**Comment by mghazizadeh** [comment]
We're looking into this. Sorry for the inconvinience

**Comment by oryband** [comment]
In the meanwhile we reverted to building the images manually on our development machines and `docker push`ing them to dockerhub. pfft.

**Comment by kentmw** [comment]
+1

**Comment by sfate** [comment]
:+1:

**Comment by rippinrobr** [comment]
All builds either automatically triggered from a github or manually triggered through dockerhub.com are failing for us with this message. Obviously this is a problem for our deployment process.

**Comment by JeanMertz** [comment]
Nasty bug this, causing lots of failures for us.

We're in the process of moving to [Quay.io](https://quay.io). Even if Docker manages to solve the issue soon, spreading the risk seems like a wise choice when considering your deployment process.

**Comment by iolufemi** [comment]
+1

**Comment by mghazizadeh** [comment]
We have found the root cause of this issue, which was impacting "organization" users kicking off builds, and have a fix in place that should resolve it for those users that were impacted by it. We realize that autobuilds are a critical part of our users CI/CD flow and are diligently working to provide a highly scalable and reliable service. Apologies for the the inconvenience you have recently encountered.

**Comment by oryband** [comment]
@mghazizadeh we are now getting the following error on builds:
```
Push failed: {"errorDetail":{"message":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/26/26bf29c0f1478110dd41a37e1a3ed93c0d00639c26d70896b578b1e7af99446e/data?Expires=1447747369\u0026Signature=WxYMRt~KPuku7TgDSmvEJUnBmK-jrrHjiCrQShlWNZdoTgjQjgPf28GiO4JOu8-AO7CzNQc-aRC86jcCke8NB57H7n27KS52nk26K-Wa0R9vQ1NuP6JdBTfAHcuLrCbABlb2rXeKSunoiB-R2RCO0XNNpNuhmbJbz0LQzt6V5Wc_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.193.202:443: i/o timeout"},"error":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/26/26bf29c0f1478110dd41a37e1a3ed93c0d00639c26d70896b578b1e7af99446e/data?Expires=1447747369\u0026Signature=WxYMRt~KPuku7TgDSmvEJUnBmK-jrrHjiCrQShlWNZdoTgjQjgPf28GiO4JOu8-AO7CzNQc-aRC86jcCke8NB57H7n27KS52nk26K-Wa0R9vQ1NuP6JdBTfAHcuLrCbABlb2rXeKSunoiB-R2RCO0XNNpNuhmbJbz0LQzt6V5Wc_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.193.202:443: i/o timeout"}
```
Automated builds are still not working. It has now been a full day where dockerhub is broken.

**Comment by iolufemi** [comment]
The error just changed. It seems the automated build built successfully, but was unable to push to the docker hubs cloudfront endpoint. See the new log below.

To achieve this, i deleted my username from the owners team on the organization. Then added my username manually as an admin to the automated build repository.

``` ---Truncated--- ---> Running in aa5c1f6df2e2 ---> 3fd2d5a1f032 Removing intermediate container aa5c1f6df2e2 Successfully built 3fd2d5a1f032 {"status":"The push refers to a repository [registry-1.docker.io/onecred/paylater-api] (len: 1)"}

{"status":"Buffering to Disk","progressDetail":{},"id":"3fd2d5a1f032"} {"status":"Pushing","progressDetail":{"current":1,"total":32},"progress":"[=\u003e ] 1 B/32 B","id":"3fd2d5a1f032"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"3fd2d5a1f032"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"3fd2d5a1f032"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"3fd2d5a1f032"} {"status":"Image successfully pushed","progressDetail":{},"id":"3fd2d5a1f032"} {"status":"Buffering to Disk","progressDetail":{},"id":"de96a3bb2427"} {"status":"Pushing","progressDetail":{"current":1,"total":32},"progress":"[=\u003e ] 1 B/32 B","id":"de96a3bb2427"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"de96a3bb2427"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"de96a3bb2427"} {"status":"Pushing","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e] 32 B/32 B","id":"de96a3bb2427"} {"status":"Image successfully pushed","progressDetail":{},"id":"de96a3bb2427"} {"status":"Buffering to Disk","progressDetail":{},"id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":32769,"total":178905},"progress":"[=========\u003e ] 32.77 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":65537,"total":178905},"progress":"[==================\u003e ] 65.54 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":98305,"total":178905},"progress":"[===========================\u003e ] 98.31 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":131073,"total":178905},"progress":"[====================================\u003e ] 131.1 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":163841,"total":178905},"progress":"[=============================================\u003e ] 163.8 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":178905,"total":178905},"progress":"[==================================================\u003e] 178.9 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":178905,"total":178905},"progress":"[==================================================\u003e] 178.9 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Pushing","progressDetail":{"current":178905,"total":178905},"progress":"[==================================================\u003e] 178.9 kB/178.9 kB","id":"28e1072fd16c"} {"status":"Image successfully pushed","progressDetail":{},"id":"28e1072fd16c"} {"status":"Buffering to Disk","progressDetail":{},"id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":294913,"total":28404143},"progress":"[\u003e ] 294.9 kB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":589825,"total":28404143},"progress":"[=\u003e ] 589.8 kB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":884737,"total":28404143},"progress":"[=\u003e ] 884.7 kB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":1179649,"total":28404143},"progress":"[==\u003e ] 1.18 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":1474561,"total":28404143},"progress":"[==\u003e ] 1.475 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":1769473,"total":28404143},"progress":"[===\u003e ] 1.769 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":2064385,"total":28404143},"progress":"[===\u003e ] 2.064 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":2359297,"total":28404143},"progress":"[====\u003e ] 2.359 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":2654209,"total":28404143},"progress":"[====\u003e ] 2.654 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":2949121,"total":28404143},"progress":"[=====\u003e ] 2.949 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":3244033,"total":28404143},"progress":"[=====\u003e ] 3.244 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":3538945,"total":28404143},"progress":"[======\u003e ] 3.539 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":3833857,"total":28404143},"progress":"[======\u003e ] 3.834 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":4128769,"total":28404143},"progress":"[=======\u003e ] 4.129 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":4423681,"total":28404143},"progress":"[=======\u003e ] 4.424 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":4718593,"total":28404143},"progress":"[========\u003e ] 4.719 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":5013505,"total":28404143},"progress":"[========\u003e ] 5.014 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":5308417,"total":28404143},"progress":"[=========\u003e ] 5.308 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":5603329,"total":28404143},"progress":"[=========\u003e ] 5.603 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":5898241,"total":28404143},"progress":"[==========\u003e ] 5.898 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":6193153,"total":28404143},"progress":"[==========\u003e ] 6.193 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":6488065,"total":28404143},"progress":"[===========\u003e ] 6.488 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":6782977,"total":28404143},"progress":"[===========\u003e ] 6.783 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":7077889,"total":28404143},"progress":"[============\u003e ] 7.078 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":7372801,"total":28404143},"progress":"[============\u003e ] 7.373 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":7667713,"total":28404143},"progress":"[=============\u003e ] 7.668 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":7962625,"total":28404143},"progress":"[==============\u003e ] 7.963 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":8257537,"total":28404143},"progress":"[==============\u003e ] 8.258 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":8552449,"total":28404143},"progress":"[===============\u003e ] 8.552 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":8847361,"total":28404143},"progress":"[===============\u003e ] 8.847 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":9142273,"total":28404143},"progress":"[================\u003e ] 9.142 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":9437185,"total":28404143},"progress":"[================\u003e ] 9.437 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":9732097,"total":28404143},"progress":"[=================\u003e ] 9.732 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":10027009,"total":28404143},"progress":"[=================\u003e ] 10.03 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":10321921,"total":28404143},"progress":"[==================\u003e ] 10.32 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":10616833,"total":28404143},"progress":"[==================\u003e ] 10.62 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":10911745,"total":28404143},"progress":"[===================\u003e ] 10.91 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":11206657,"total":28404143},"progress":"[===================\u003e ] 11.21 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":11501569,"total":28404143},"progress":"[====================\u003e ] 11.5 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":11796481,"total":28404143},"progress":"[====================\u003e ] 11.8 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":12091393,"total":28404143},"progress":"[=====================\u003e ] 12.09 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":12386305,"total":28404143},"progress":"[=====================\u003e ] 12.39 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":12681217,"total":28404143},"progress":"[======================\u003e ] 12.68 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":12976129,"total":28404143},"progress":"[======================\u003e ] 12.98 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":13271041,"total":28404143},"progress":"[=======================\u003e ] 13.27 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":13565953,"total":28404143},"progress":"[=======================\u003e ] 13.57 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":13860865,"total":28404143},"progress":"[========================\u003e ] 13.86 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":14155777,"total":28404143},"progress":"[========================\u003e ] 14.16 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":14450689,"total":28404143},"progress":"[=========================\u003e ] 14.45 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":14745601,"total":28404143},"progress":"[=========================\u003e ] 14.75 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":15040513,"total":28404143},"progress":"[==========================\u003e ] 15.04 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":15335425,"total":28404143},"progress":"[==========================\u003e ] 15.34 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":15630337,"total":28404143},"progress":"[===========================\u003e ] 15.63 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":15925249,"total":28404143},"progress":"[============================\u003e ] 15.93 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":16220161,"total":28404143},"progress":"[============================\u003e ] 16.22 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":16515073,"total":28404143},"progress":"[=============================\u003e ] 16.52 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":16809985,"total":28404143},"progress":"[=============================\u003e ] 16.81 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":17104897,"total":28404143},"progress":"[==============================\u003e ] 17.1 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":17399809,"total":28404143},"progress":"[==============================\u003e ] 17.4 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":17694721,"total":28404143},"progress":"[===============================\u003e ] 17.69 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":17989633,"total":28404143},"progress":"[===============================\u003e ] 17.99 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":18284545,"total":28404143},"progress":"[================================\u003e ] 18.28 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":18579457,"total":28404143},"progress":"[================================\u003e ] 18.58 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":18874369,"total":28404143},"progress":"[=================================\u003e ] 18.87 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":19169281,"total":28404143},"progress":"[=================================\u003e ] 19.17 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":19464193,"total":28404143},"progress":"[==================================\u003e ] 19.46 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":19759105,"total":28404143},"progress":"[==================================\u003e ] 19.76 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":20054017,"total":28404143},"progress":"[===================================\u003e ] 20.05 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":20348929,"total":28404143},"progress":"[===================================\u003e ] 20.35 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":20643841,"total":28404143},"progress":"[====================================\u003e ] 20.64 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":20938753,"total":28404143},"progress":"[====================================\u003e ] 20.94 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":21233665,"total":28404143},"progress":"[=====================================\u003e ] 21.23 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":21528577,"total":28404143},"progress":"[=====================================\u003e ] 21.53 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":21823489,"total":28404143},"progress":"[======================================\u003e ] 21.82 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":22118401,"total":28404143},"progress":"[======================================\u003e ] 22.12 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":22413313,"total":28404143},"progress":"[=======================================\u003e ] 22.41 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":22708225,"total":28404143},"progress":"[=======================================\u003e ] 22.71 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":23003137,"total":28404143},"progress":"[========================================\u003e ] 23 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":23298049,"total":28404143},"progress":"[=========================================\u003e ] 23.3 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":23592961,"total":28404143},"progress":"[=========================================\u003e ] 23.59 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":23887873,"total":28404143},"progress":"[==========================================\u003e ] 23.89 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":24182785,"total":28404143},"progress":"[==========================================\u003e ] 24.18 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":24477697,"total":28404143},"progress":"[===========================================\u003e ] 24.48 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":24772609,"total":28404143},"progress":"[===========================================\u003e ] 24.77 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":25067521,"total":28404143},"progress":"[============================================\u003e ] 25.07 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":25362433,"total":28404143},"progress":"[============================================\u003e ] 25.36 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":25657345,"total":28404143},"progress":"[=============================================\u003e ] 25.66 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":25952257,"total":28404143},"progress":"[=============================================\u003e ] 25.95 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":26247169,"total":28404143},"progress":"[==============================================\u003e ] 26.25 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":26542081,"total":28404143},"progress":"[==============================================\u003e ] 26.54 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":26836993,"total":28404143},"progress":"[===============================================\u003e ] 26.84 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":27131905,"total":28404143},"progress":"[===============================================\u003e ] 27.13 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":27426817,"total":28404143},"progress":"[================================================\u003e ] 27.43 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":27721729,"total":28404143},"progress":"[================================================\u003e ] 27.72 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":28016641,"total":28404143},"progress":"[=================================================\u003e ] 28.02 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":28311553,"total":28404143},"progress":"[=================================================\u003e ] 28.31 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":28404143,"total":28404143},"progress":"[==================================================\u003e] 28.4 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Pushing","progressDetail":{"current":28404143,"total":28404143},"progress":"[==================================================\u003e] 28.4 MB/28.4 MB","id":"e190f64bd30f"} {"status":"Image successfully pushed","progressDetail":{},"id":"e190f64bd30f"} {"status":"Buffering to Disk","progressDetail":{},"id":"fca8e78f5a11"} {"status":"Pushing","progressDetail":{"current":756,"total":756},"progress":"[==================================================\u003e] 756 B/756 B","id":"fca8e78f5a11"} {"status":"Pushing","progressDetail":{"current":756,"total":756},"progress":"[==================================================\u003e] 756 B/756 B","id":"fca8e78f5a11"} {"status":"Pushing","progressDetail":{"current":756,"total":756},"progress":"[==================================================\u003e] 756 B/756 B","id":"fca8e78f5a11"} {"status":"Image successfully pushed","progressDetail":{},"id":"fca8e78f5a11"} {"status":"Buffering to Disk","progressDetail":{},"id":"507fb46b20c9"} {"status":"Pushing","progressDetail":{"current":384,"total":384},"progress":"[==================================================\u003e] 384 B/384 B","id":"507fb46b20c9"} {"status":"Pushing","progressDetail":{"current":384,"total":384},"progress":"[==================================================\u003e] 384 B/384 B","id":"507fb46b20c9"} {"status":"Pushing","progressDetail":{"current":384,"total":384},"progress":"[==================================================\u003e] 384 B/384 B","id":"507fb46b20c9"} {"status":"Image successfully pushed","progressDetail":{},"id":"507fb46b20c9"} {"status":"Buffering to Disk","progressDetail":{},"id":"2e0ee8501a36"} {"status":"Pushing","progressDetail":{"current":191,"total":191},"progress":"[==================================================\u003e] 191 B/191 B","id":"2e0ee8501a36"} {"status":"Pushing","progressDetail":{"current":191,"total":191},"progress":"[==================================================\u003e] 191 B/191 B","id":"2e0ee8501a36"} {"status":"Pushing","progressDetail":{"current":191,"total":191},"progress":"[==================================================\u003e] 191 B/191 B","id":"2e0ee8501a36"} {"errorDetail":{"message":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/d6/d65fcbca9ac14737fe7be24321bb1eb929059297770e12f65a12df76854908bf/data?Expires=1447750540\u0026Signature=Vv03wbetWaDByZ40k3DD5RqCnV-XN2pbGPuuNlB~Hsb4Q~cXayWpcyjHeGdJlCS-LkMrVrjlM6VmIItMHUveghAkgRyMLvjF980wmotu09ff1YrnpUKnN43V4SICMgXFeihXcDCQxeRolhD73l8z5mMIfOmdngEWtmNO6O3Roas_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.194.90:443: i/o timeout"},"error":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/d6/d65fcbca9ac14737fe7be24321bb1eb929059297770e12f65a12df76854908bf/data?Expires=1447750540\u0026Signature=Vv03wbetWaDByZ40k3DD5RqCnV-XN2pbGPuuNlB~Hsb4Q~cXayWpcyjHeGdJlCS-LkMrVrjlM6VmIItMHUveghAkgRyMLvjF980wmotu09ff1YrnpUKnN43V4SICMgXFeihXcDCQxeRolhD73l8z5mMIfOmdngEWtmNO6O3Roas_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.194.90:443: i/o timeout"} ```

**Comment by mghazizadeh** [comment]
https://github.com/docker/hub-feedback/issues/466 

Unrelated to the issue here.. We are on it!

**Comment by oryband** [comment]
this is resolved for us. 2-day outage :\

**Comment by oryband** [comment]
@mghazizadeh feel free to close this
