### ISSUE TITLE
Dockerfile not displaying in web interface

### ISSUE THREAD

**Issue by chrisvire** [docker/hub-feedback#492]
We created a new repository (silintl/appbuilder-jenkins).  At first, it wouldn't build.  There seemed to be an issue with bitbucket at the time (it was taking a long time for me to clone the source repo and push to it -- actually timeout on my machine to push the first time -- I was trying to trigger an update and a new build).

So we finally got a build.  However, the Dockerfile is not displaying in the web interface.  I suspect that the code is not handling git timing out very well.

**Comment by adriaandejonge** [comment]
Same issue here with adejonge/storm-base (and others) but then based on Github instead of Bitbucket.

**Comment by lukebennett** [comment]
I also have this problem with lukebennett/hugo (via Github). No issues with the builds running, I just don't have my Dockerfile or readme pulling through.

**Comment by murali44** [comment]
Same issue here. The image is getting built, but the Dockerfile does not show up. I'm using github.

**Comment by mandheer** [comment]
Same here. I've created the docker file and it's not reflected at my Dockerfile TAB

**Comment by mandheer** [comment]
Aww .. It's showing now .. After first Successful build ... I'm using github for code repo.

**Comment by FreeSlave** [comment]
Should Dockerfile appear automatically?
I used 
```
docker push username/repository:tag
```
to push image on docker hub, but it does not show "Dockefile" tab like in other public repos.

**Comment by hkirsman** [comment]
+1, what's the deal with that? I also see some people have bitbucket url on the right

**Comment by LeonGravel** [comment]
Same here

**Comment by qhh0205** [comment]
Same here, it sames new UI droped the Dockerfile tab?

**Comment by cniekerk** [comment]
Our old repositories (with automated builds) have the Dockerfile tab still being displayed, but newly created repositories (with automated builds) no longer have this tab displayed.

Could we please get it back? Was this intentional or by accident?

**Comment by cniekerk** [comment]
Also related things are missing, like links back to the GitHub project etc.

**Comment by qhh0205** [comment]
@chrisvire Yes, same to me, waiting for an official response...

**Comment by meticulous-dft** [comment]
Thanks for patience. We are actively working on this. Will bring changes early next week.

**Comment by snakeskinsalamander** [comment]
are there any updates?

**Comment by meticulous-dft** [comment]
Should be fixed.

**Comment by qhh0205** [comment]
@meticulous-dft 
Thank you, but it seems to be visible only after login. So how do i see the Dockerfile and github link tab without login?

![image](https://user-images.githubusercontent.com/12775142/51780229-ca2f4180-2147-11e9-9f57-5940860acdab.png)

**Comment by cniekerk** [comment]
@meticulous-dft @qhh0205 I am experiencing exactly the same. Is this purely a caching problem or was this done by accident or on purpose?

**Comment by qhh0205** [comment]
@cniekerk it seems must login othewise cant see the Dockerfile tab and github link.

**Comment by cniekerk** [comment]
@meticulous-dft Can this issue be reopened please? I do not feel that this has been fixed yet.

**Comment by cniekerk** [comment]
@meticulous-dft I see the problem has been fixed now. Thank you very much!

**Comment by jasperf** [comment]
I synched / connected our repo https://hub.docker.com/r/smart48/laravel-app with https://github.com/smart48/laravel-app , I did build, but I still do not see the `Dockerfile`. So what am I missing here?

**Comment by jasperf** [comment]
Never mind. In my case I realized it was not done doing its first triggered build. Done now and all is shown.
