### ISSUE TITLE
When creating a new Github auto build, list of organizations is incorrect

### ISSUE THREAD

**Issue by JesseCrocker** [docker/hub-feedback#577]
List of github orgs shown when trying to create a new auto build. Im not a member of clevland-metro-parks and never have been, though they have forked one of my repos. One of the orgs that I am a member of, hemamaps, does not show up.
![screen shot 2016-02-11 at 8 17 12 am](https://cloud.githubusercontent.com/assets/2048291/12980055/ed3ee242-d097-11e5-8489-25c052f35bf7.png)

Screenshot of github showing orgs i am a member of:
![screen shot 2016-02-11 at 8 19 25 am](https://cloud.githubusercontent.com/assets/2048291/12980123/4387bb56-d098-11e5-9901-0651542868a3.png)

I would appreciate help resolving this issue, as I need to create several auto builds on the org that is not showing up.

**Comment by kizbitz** [comment]
Hi Jesse,

Thanks, for reporting. I just responded to your ticket at https://support.docker.com. We'll get this resolved for you there.

Closing here...

**Comment by bcwalrus** [comment]
When you do `curl https://api.github.com/user/repos`, Github has changed their API to return *all the forks* of your repos. Github said that it's a bug on their side. We're working with them to address this issue.

**Comment by bcwalrus** [comment]
**Update:** This issue has been resolved, thanks to Github for fixing their API.

**Comment by jingpengwu** [comment]
I still have this problem. I am a member of an organization in GitHub, but can not see that in docker hub!

**Comment by bcwalrus** [comment]
@jingpengwu Docker Hub does not show Github organization membership. It's showing the repos that you have, according to the `/user/repos` API (https://developer.github.com/v3/repos/#list-your-repositories). Those repos are then grouped by Github orgs.

For example, if you belong to a Github org but can't access any of its repos, then that Github org won't show up.

If you still think there's something wrong, could you see if that Github repo is found in `https://api.github.com/user/repos`?

**Comment by jingpengwu** [comment]
Thanks for the information. Finally, I found that the problem is in my own `personal setting`. I should grant access for the organization in the `OAuth applications`.
