### ISSUE TITLE
Bug with automated builds and ADD / stat command

### ISSUE THREAD

**Issue by domibarton** [docker/hub-feedback#811]
Hi

I've an issue with my automated build and I'm sure it's a bug!

Here's the error message I'll get:

```
stat /var/lib/docker/overlay/b0d9f4dd0f11184a2653979037fc63d14632a928b4bcf71b972214b33544182d/merged/sabnzbd.sh: no such file or directory
```

Though, there's something weird. I've 2 Docker Hub repositories linked to the SAME github repository:
- [dbarton/sabnzbd](https://hub.docker.com/r/dbarton/sabnzbd)
- [sabnzbd/sabnzbd](https://hub.docker.com/r/sabnzbd/sabnzbd)

Both repositories are automated builds and were triggered when I commited into the `develop` branch. Funnily enough only `dbarton/sabnzbd` was [built successfully](https://hub.docker.com/r/dbarton/sabnzbd/builds/bsbrlhrmzd6jakhdg8mhz4d/), while `sabnzbd/sabnzbd` [failed with an error](https://hub.docker.com/r/sabnzbd/sabnzbd/builds/beb9aobhzuwhplby2t3vqza/).  Again, it's the same github repo and the exactly same source!

I've triggered the failed build manually again and it still fails!

Cheers
Domi

**Comment by domibarton** [comment]
Guess what - third time is the charm.
I triggered a manual build 3 times and then it worked (same github repo, same source, nothing changed).

**Comment by ulrichSchreiner** [comment]
hi,

i have the same problem with my automated builds.

```
---
Step 11 : COPY entry.sh /entry.sh
Removing intermediate container 82d0488e67f3
stat /var/lib/docker/overlay/bcf21515664a471296704ea9525f9c3a1065e41669e25faeb082c73280e10a25/merged/entry.sh: no such file or directory
```
local build works using docker 1.12 and aufs.

</usc>

**Comment by ryansanford** [comment]
I'm having this error as well with dockerhub automated builds. Had it as well September 30, around 8 AM Central time, and it went away by 11 AM Central time. Now this error is back again. 

https://hub.docker.com/r/scitran/core/builds/bewh2pepxjphhpgqcyijt2f/

```
Step 20 : COPY docker/inject_build_info.sh /
Removing intermediate container 6145f78c8917
stat /var/lib/docker/overlay/c1cd12227f0b77ca69502dce8d9d7cae4bc2af9a34a8298ed3cb5db3d113028e/merged/inject_build_info.sh: no such file or directory
```

**Comment by domibarton** [comment]
Current workaround: Just trigger it again… and again… and again ;) After a couple of times it works!

**Comment by robertBrem** [comment]
+1
Also tried copy instead of add.
robertbrem/jenkins

**Comment by hardware** [comment]
Same issue here : https://hub.docker.com/r/hardware/mailserver/builds/b6smxq3zq7fdtzwmyqjbhra/

```
Step 7 : COPY rootfs /
Removing intermediate container a073e4b98b3e
lchown /var/lib/docker/overlay/673a8cc98f9cc7b3c815406edd258b5ec4192a4b74034db5a2d7184e5750b488/merged/etc: no such file or directory
```

> Current workaround: Just trigger it again… and again… and again ;) After a couple of times it works!

I tried 6 times :/

**Comment by edwintorok** [comment]
Same issue here: https://hub.docker.com/r/skylable/libres3/builds/b5eyuuvrkhgzhifvjlx87f8/
Building on my own machine with docker 1.12.2-rc1, and devicemapper works, workaround: `docker login`, build locally, `docker push ....`

**Comment by domibarton** [comment]
The same issue…

* [here…](https://hub.docker.com/r/dbarton/utorrent/builds/balvygf9ttptzitfnlmygws/)
* [here…](https://hub.docker.com/r/dbarton/utorrent/builds/bfysqbkemqx2dmycnvbzn9d/)
* [here…](https://hub.docker.com/r/dbarton/utorrent/builds/bg3rteymffivnrzjbct6pzy/)
* [here…](https://hub.docker.com/r/dbarton/utorrent/builds/baaxbgmskw65fikahlqppol/)
* [and here!](https://hub.docker.com/r/dbarton/utorrent/builds/bwfgacgsiqdbjare7rpwxye/)

Has anyone attention to this issue?

**Comment by pkennedyr** [comment]
Thanks for the feedback. The team is aware of the issue and is actively working on a fix.

**Comment by frekele** [comment]
same issue that: https://github.com/docker/hub-feedback/issues/811

**Comment by frekele** [comment]
17 days and are still with the problem unsolved.

We are questioning whether docker hub is really reliable to use in production.

We use docker hub in production and we are concerned about this, because it is making difficult our work.

I paid monthly for 50 private repositories.

you have any predictions for Rollback ou Correction?

Related too: https://forums.docker.com/t/automated-docker-build-fails/22831

**Comment by pkennedyr** [comment]
UPDATE: Last week, we rolled back a change to the automated build system that was believed to be causing these intermittent build failures. However, a small percentage of overall build traffic is still experiencing this issue, so the team is actively working to address a fix and will be releasing another update early this week.

We apologize for the inconvenience and will continue posting updates to this thread and #821 as further information is available.

**Comment by domibarton** [comment]
@pkennedyr thanks for the update!

**Comment by xezpeleta** [comment]
Same problem here: https://hub.docker.com/r/elkarbackup/elkarbackup/builds/

Thanks

**Comment by frekele** [comment]
@pkennedyr thanks for the feedback!

**Comment by keimoon** [comment]
We still got the same error with every build. Our current work around is to permute ADD commands in every commit and hope.

**Comment by hwdsl2** [comment]
Related: docker/docker#25925

**Comment by ryanwalls** [comment]
FYI.  As of today, I am still hitting this issue.

**Comment by oliveiraev** [comment]
I think that I'm having the same issue
https://hub.docker.com/r/visie/debian/builds/bhxqkwbg8lvdwg9b8irixac/
consecutive builds didn't work

**Comment by jsh2134** [comment]
I am also getting this issue

**Comment by Gibby** [comment]
Experiencing this issue as well, 13 failures before a successful one.

**Comment by pkennedyr** [comment]
UPDATE: As of this morning (11:50 am PDT), the absolute root cause of this issue has not yet been identified and ~6% of overall build traffic is still experiencing this issue. We have strong reason to believe that it is related to the following Docker engine issue: docker/docker#25925

We are treating this issue as a top priority across Docker and the team is actively working to address it. We apologize for the inconvenience and will update this thread as soon further information is available.

**Comment by derekdon** [comment]
Also experiencing this issue.

**Comment by 60days** [comment]
Moving the failing .sh scripts ADD/COPY target out of the root dir has resolved this for me across 6 containers.

**Comment by adolfogc** [comment]
Hello, today I'm also experiencing this issue.

**Comment by eugene-s** [comment]
Hi, I have the same problem.
https://hub.docker.com/r/eugenes1/python-sshd/builds/bumgao6ycvs7wtsijhyrp2g/

**Comment by bhuisgen** [comment]
Same problem here : https://hub.docker.com/r/bhuisgen/alpine-base/builds/

Is it a problem with docker 1.12.2 and shall we wait for the upcoming 1.12.3 ?

**Comment by loskov** [comment]
Got the same problem with: [](https://hub.docker.com/r/softwareplant/jira/builds/)
After 3 errors builds it succeeded spontaneously.

**Comment by 60days** [comment]
Moving the failing .sh scripts ADD/COPY target out of the root dir has
resolved this for me across 6 containers.

**Comment by pkennedyr** [comment]
UPDATE: The root cause of this issue has been identified and a temporary fix was deployed to production last night (11pm PDT), which has prevented subsequent occurrences of this issue. The upcoming release of Docker engine 1.12.3 includes an update that we have strong reason to believe will address the root cause of this issue. The team continues to treat this as a top priority and we will be updating this thread as more information is available.

**Comment by oliveiraev** [comment]
> Moving the failing .sh scripts ADD/COPY target out of the root dir has
> resolved this for me across 6 containers.

mee too

**Comment by pkennedyr** [comment]
UPDATE: Docker engine 1.12.3 includes an update which addressed the root cause of this build failure. After upgrading the Docker autobuild service to Docker engine 1.12.3, we believe the issue has been resolved as subsequent occurrences of these build failures are no longer occurring. We apologize for the inconvenience and are taking steps to prevent similar issues from occurring in the future.

**Comment by tangramor** [comment]
I met the same problem on COPY file in my automated buildings. But I can successfully build in on my workstation.

https://hub.docker.com/r/tangramor/docker-tars-node/builds/bbpjqtcdxxa7vuhqj4jb2sl/

Step 25/31 : COPY install_node.sh /root/init/ 
COPY failed: stat /var/lib/docker/tmp/docker-builder446545312/install_node.sh: no such file or directory

**Comment by marwan-at-work** [comment]
I am still experiencing this issue as my local docker recognizes the `vendor` folder that was COPY'd but docker hub's build does not see it when running `go build -mod=vendor`

**Comment by garritfra** [comment]
> I met the same problem on COPY file in my automated buildings. But I can successfully build in on my workstation.

Same for me. Seems to me like this still isn't sesolved...

https://cloud.docker.com/repository/registry-1.docker.io/garritfra/ditto/builds/c52b3572-970b-4257-ab7f-65ff63be8940

**Comment by brindsoft** [comment]
still same problem
Step 11/30 : COPY requirement.txt /opt/odoo/odoo/requirements-extra.txt
COPY failed: stat /var/lib/docker/tmp/docker-builder954328513/requirement.txt: no such file or directory

**Comment by dwalintukan** [comment]
Having the same issue. Is there really no solution?

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Switched to a new branch '2.2.1'
Executing build hook...
Running hooks/build...
Sending build context to Docker daemon 19.46kB
Step 1/28 : FROM dwalintukan/bionic-elixir-phoenix:1.8.2
1.8.2: Pulling from dwalintukan/bionic-elixir-phoenix
38e2e6cd5626: Pulling fs layer
705054bc3f5b: Pulling fs layer
c7051e069564: Pulling fs layer
7308e914506c: Pulling fs layer
2381539d2fbf: Pulling fs layer
e5af5b279041: Pulling fs layer
ccfc564137d3: Pulling fs layer
212415945a6a: Pulling fs layer
81e9e00fb124: Pulling fs layer
5c7c819fc96b: Pulling fs layer
c93fccc7062a: Pulling fs layer
365301bab15e: Pulling fs layer
cdca5fc1836c: Pulling fs layer
7308e914506c: Waiting
2381539d2fbf: Waiting
e5af5b279041: Waiting
ccfc564137d3: Waiting
212415945a6a: Waiting
81e9e00fb124: Waiting
5c7c819fc96b: Waiting
c93fccc7062a: Waiting
365301bab15e: Waiting
cdca5fc1836c: Waiting
705054bc3f5b: Verifying Checksum
705054bc3f5b: Download complete
c7051e069564: Verifying Checksum
c7051e069564: Download complete
7308e914506c: Verifying Checksum
7308e914506c: Download complete
e5af5b279041: Verifying Checksum
e5af5b279041: Download complete
38e2e6cd5626: Verifying Checksum
38e2e6cd5626: Download complete
2381539d2fbf: Verifying Checksum
2381539d2fbf: Download complete
81e9e00fb124: Verifying Checksum
81e9e00fb124: Download complete
212415945a6a: Verifying Checksum
212415945a6a: Download complete
c93fccc7062a: Verifying Checksum
c93fccc7062a: Download complete
365301bab15e: Verifying Checksum
365301bab15e: Download complete
cdca5fc1836c: Verifying Checksum
cdca5fc1836c: Download complete
ccfc564137d3: Verifying Checksum
ccfc564137d3: Download complete
5c7c819fc96b: Verifying Checksum
5c7c819fc96b: Download complete
38e2e6cd5626: Pull complete
705054bc3f5b: Pull complete
c7051e069564: Pull complete
7308e914506c: Pull complete
2381539d2fbf: Pull complete
e5af5b279041: Pull complete
ccfc564137d3: Pull complete
212415945a6a: Pull complete
81e9e00fb124: Pull complete
5c7c819fc96b: Pull complete
c93fccc7062a: Pull complete
365301bab15e: Pull complete
cdca5fc1836c: Pull complete
Digest: sha256:ef55cf8bbf667191261736ef8b27861b6c0ed97c8bfbe2c750945d6bcb8dfbe4
Status: Downloaded newer image for dwalintukan/bionic-elixir-phoenix:1.8.2
---> 71ad9b9fc296
Step 2/28 : RUN apt-get -y install make gcc build-essential automake libtool inotify-tools autoconf libgmp3-dev
---> Running in 2716c8631353
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
make set to manually installed.
inotify-tools is already the newest version (3.14-2).
gcc is already the newest version (4:7.4.0-1ubuntu2.3).
gcc set to manually installed.
The following additional packages will be installed:
autotools-dev libgmp-dev libgmpxx4ldbl libltdl-dev libltdl7 libsigsegv2 m4
Suggested packages:
autoconf-archive gnu-standards autoconf-doc gettext gmp-doc libgmp10-doc
libmpfr-dev libtool-doc gfortran | fortran95-compiler gcj-jdk m4-doc
The following NEW packages will be installed:
autoconf automake autotools-dev libgmp-dev libgmp3-dev libgmpxx4ldbl
libltdl-dev libltdl7 libsigsegv2 libtool m4
0 upgraded, 11 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,804 kB of archives.
After this operation, 8,310 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libsigsegv2 amd64 2.12-1 [14.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 m4 amd64 1.4.18-1 [197 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 autoconf all 2.69-11 [322 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 autotools-dev all 20180224.1 [39.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 automake all 1:1.15.1-3ubuntu2 [509 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgmpxx4ldbl amd64 2:6.1.2+dfsg-2 [8,964 B]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgmp-dev amd64 2:6.1.2+dfsg-2 [316 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgmp3-dev amd64 2:6.1.2+dfsg-2 [1,996 B]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 libltdl7 amd64 2.4.6-2 [38.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 libltdl-dev amd64 2.4.6-2 [162 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 libtool all 2.4.6-2 [194 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1,804 kB in 1s (2,050 kB/s)
Selecting previously unselected package libsigsegv2:amd64.
(Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 39790 files and directories currently installed.)
Preparing to unpack .../00-libsigsegv2_2.12-1_amd64.deb ...
Unpacking libsigsegv2:amd64 (2.12-1) ...
Selecting previously unselected package m4.
Preparing to unpack .../01-m4_1.4.18-1_amd64.deb ...
Unpacking m4 (1.4.18-1) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../02-autoconf_2.69-11_all.deb ...
Unpacking autoconf (2.69-11) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../03-autotools-dev_20180224.1_all.deb ...
Unpacking autotools-dev (20180224.1) ...
Selecting previously unselected package automake.
Preparing to unpack .../04-automake_1%3a1.15.1-3ubuntu2_all.deb ...
Unpacking automake (1:1.15.1-3ubuntu2) ...
Selecting previously unselected package libgmpxx4ldbl:amd64.
Preparing to unpack .../05-libgmpxx4ldbl_2%3a6.1.2+dfsg-2_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-2) ...
Selecting previously unselected package libgmp-dev:amd64.
Preparing to unpack .../06-libgmp-dev_2%3a6.1.2+dfsg-2_amd64.deb ...
Unpacking libgmp-dev:amd64 (2:6.1.2+dfsg-2) ...
Selecting previously unselected package libgmp3-dev.
Preparing to unpack .../07-libgmp3-dev_2%3a6.1.2+dfsg-2_amd64.deb ...
Unpacking libgmp3-dev (2:6.1.2+dfsg-2) ...
Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../08-libltdl7_2.4.6-2_amd64.deb ...
Unpacking libltdl7:amd64 (2.4.6-2) ...
Selecting previously unselected package libltdl-dev:amd64.
Preparing to unpack .../09-libltdl-dev_2.4.6-2_amd64.deb ...
Unpacking libltdl-dev:amd64 (2.4.6-2) ...
Selecting previously unselected package libtool.
Preparing to unpack .../10-libtool_2.4.6-2_all.deb ...
Unpacking libtool (2.4.6-2) ...
Setting up libsigsegv2:amd64 (2.12-1) ...
Setting up m4 (1.4.18-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up autotools-dev (20180224.1) ...
Setting up libltdl7:amd64 (2.4.6-2) ...
Setting up libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-2) ...
Setting up libtool (2.4.6-2) ...
Setting up libgmp-dev:amd64 (2:6.1.2+dfsg-2) ...
Setting up libltdl-dev:amd64 (2.4.6-2) ...
Setting up autoconf (2.69-11) ...
Setting up automake (1:1.15.1-3ubuntu2) ...
update-alternatives: using /usr/bin/automake-1.15 to provide /usr/bin/automake (automake) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/automake.1.gz because associated file /usr/share/man/man1/automake-1.15.1.gz (of link group automake) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/aclocal.1.gz because associated file /usr/share/man/man1/aclocal-1.15.1.gz (of link group automake) doesn't exist
Setting up libgmp3-dev (2:6.1.2+dfsg-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Removing intermediate container 2716c8631353
---> c48baa88e9ae
Step 3/28 : ARG PORT
---> Running in 865d5f94df90
Removing intermediate container 865d5f94df90
---> f829a04f84cc
Step 4/28 : ARG MIX_ENV
---> Running in 378789df84fa
Removing intermediate container 378789df84fa
---> b91cff818bc8
Step 5/28 : ARG NETWORK
---> Running in 7cedf1455ba7
Removing intermediate container 7cedf1455ba7
---> a9e30035ccc1
Step 6/28 : ARG SUBNETWORK
---> Running in cd1baf2117b3
Removing intermediate container cd1baf2117b3
---> ac272ba2dc5b
Step 7/28 : ARG COIN
---> Running in 4e91951e0d6e
Removing intermediate container 4e91951e0d6e
---> 91726305f518
Step 8/28 : ARG ETHEREUM_JSONRPC_VARIANT
---> Running in 4b3a9da3ffe2
Removing intermediate container 4b3a9da3ffe2
---> a8504855e521
Step 9/28 : ARG ETHEREUM_JSONRPC_HTTP_URL
---> Running in 4d6ba6cc8b27
Removing intermediate container 4d6ba6cc8b27
---> c834fd7c007a
Step 10/28 : ARG ETHEREUM_JSONRPC_WS_URL
---> Running in 39ae6d12866e
Removing intermediate container 39ae6d12866e
---> 0894a57b2a01
Step 11/28 : ARG DATABASE_URL
---> Running in 1aa4e0b0740c
Removing intermediate container 1aa4e0b0740c
---> 598169bb2418
Step 12/28 : ARG SECRET_KEY_BASE
---> Running in ec363b247531
Removing intermediate container ec363b247531
---> be765247ce0c
Step 13/28 : ARG ECTO_USE_SSL
---> Running in e3a75ee19bcb
Removing intermediate container e3a75ee19bcb
---> 494bd630e7a4
Step 14/28 : ENV PORT=$PORT MIX_ENV=$MIX_ENV NETWORK=$NETWORK SUBNETWORK=$SUBNETWORK COIN=$COIN ETHEREUM_JSONRPC_VARIANT=$ETHEREUM_JSONRPC_VARIANT ETHEREUM_JSONRPC_HTTP_URL=$ETHEREUM_JSONRPC_HTTP_URL ETHEREUM_JSONRPC_WS_URL=$ETHEREUM_JSONRPC_WS_URL DATABASE_URL=$DATABASE_URL SECRET_KEY_BASE=$SECRET_KEY_BASE ECTO_USE_SSL=$ECTO_USE_SSL
---> Running in 315b502041a3
Removing intermediate container 315b502041a3
---> e70b916ab8ad
Step 15/28 : EXPOSE $PORT
---> Running in c2b2e25c23c3
Removing intermediate container c2b2e25c23c3
---> 6f06cef8e7cf
Step 16/28 : HEALTHCHECK CMD curl -f "http://localhost:$PORT" || exit 1
---> Running in 621c2b167034
Removing intermediate container 621c2b167034
---> bc7e4e671f69
Step 17/28 : COPY mix.exs mix.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder238776522/mix.exs: no such file or directory
build hook failed! (1)
```

**Comment by brindsoft** [comment]
> still same problem. Strange even after years you guys couldn't fix it.
> Step 11/30 : COPY requirement.txt /opt/odoo/odoo/requirements-extra.txt
> COPY failed: stat /var/lib/docker/tmp/docker-builder954328513/requirement.txt: no such file or directory

In my Case my automatic build was mis configured. I had this 
![Screenshot](https://user-images.githubusercontent.com/51924245/61886348-6ff51a80-aef7-11e9-93a4-adb85c26180e.png)

but in my case correct was 
![correct](https://user-images.githubusercontent.com/51924245/61886411-95822400-aef7-11e9-93bf-52e6d10d6c24.png)

**Comment by ReSearchITEng** [comment]
The Build Context is no longer an option available in 2019 (the column is missing), and builds are failing with this issue...

**Comment by ReSearchITEng** [comment]
Found it, it was moved post definition: https://forums.docker.com/t/docker-build-failing-on-docker-hub/76191
